### ISSUE TITLE
Timeline range

### ISSUE THREAD

**Issue by vtproject** [lazarchik/visualtracker#1]
Timeline.pd canvas is not extended above time ruler, canvases can not be placed above tracks. You can not mute module output unless you move it to a muted track or delete it.

**Comment by lzref** [comment]
Fixed. I moved timeline abstraction 90 pixels up. I started sending mouse messages with y coordinate (adding 90 pixels) correction from the VT timeline window to the timeline abstraction (see "pd $0-mouse-input" in the timeline window).

I also had to modify the connector abstraction in order to also apply 90 pixels of vertical correction when sending/receiving object positions and determining the current track number.

I also had to remove some code from "pd delete_modules" so that it doesn't delete the timeline abstraction.
