### ISSUE TITLE
Color table

### ISSUE THREAD

**Issue by vtproject** [lazarchik/visualtracker#2]
Not using default color table mapping - canvas colors do not match with module color - check pd program/colortable:

![image](https://cloud.githubusercontent.com/assets/12696868/8269775/ba07c7b4-17b9-11e5-8ebf-a7da6a6c4cc6.png)

**Comment by lzref** [comment]
We should probably change the color table to use RGB instead of a list of predefined canvas colors. Data structures don't support predefined canvas colors, only RGB. They do it in a weird way, only allowing values from 0 to 9 for each component, but we can scale them as long as colors are represented as RGB.

Another problem is that color table doesn't have entries after index 13 (if I recall correctly). Values after that are super huge (-7.14251e+06 and so on).

And finally, some of the colors currently chosen poorly so that black text can barely be read on them. We should probably choose only light colors.

**Comment by vtproject** [comment]
Changed colortable do work with RGB:
![image](https://cloud.githubusercontent.com/assets/12696868/8635581/6b2dfe9e-2829-11e5-8ccc-d268a0e361ff.png)

Specific colors can be tweaked later.

In which syntax do you need color numbers for data structures? Just this big number or separate RBG values?

**Comment by lzref** [comment]
Fixed in commit 19e731a2afd7d2470614406376135353db6e7ff0. Data structures use a very weird color format: a number from 0 to 999 where each digit represents one of RGB components. I added a second color table for them. I populated the tables with 20 matching colors that are light enough to see black text on them. I also had to modify the connector and all modules abstractions in order to use a number from 0 to 20 as a color instead of huge numbers (where all RGB components are mixed together).
